FROM python:3.6-alpine
MAINTAINER Kevin Travers "kevtraver1@gmail.com"
COPY . /app
WORKDIR /app
RUN python3 -m venv venv
RUN venv/bin/pip3 install -r requirements.txt
RUN pip3 install -r requirements.txt
EXPOSE 5000
ENTRYPOINT ["python3"]
CMD ["app.py"]
